//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "SpawnDev_Crypto.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_SpawnDev_Crypto_SpawnDev_Crypto_Ed25519::GenerateKeyPair___STATIC__VOID__SZARRAY_U1__SZARRAY_U1,
    Library_SpawnDev_Crypto_SpawnDev_Crypto_Ed25519::KeyPairFromSeed___STATIC__VOID__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1,
    Library_SpawnDev_Crypto_SpawnDev_Crypto_Ed25519::Sign___STATIC__VOID__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1,
    Library_SpawnDev_Crypto_SpawnDev_Crypto_Ed25519::Verify___STATIC__BOOLEAN__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1,
    Library_SpawnDev_Crypto_SpawnDev_Crypto_X25519::GeneratePrivateKey___STATIC__VOID__SZARRAY_U1,
    Library_SpawnDev_Crypto_SpawnDev_Crypto_X25519::GetPublicKey___STATIC__VOID__SZARRAY_U1__SZARRAY_U1,
    Library_SpawnDev_Crypto_SpawnDev_Crypto_X25519::SharedSecret___STATIC__VOID__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SpawnDev_Crypto =
{
    "SpawnDev.Crypto",
    0xEB181134,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
