//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef SPAWNDEV_CRYPTO_H
#define SPAWNDEV_CRYPTO_H

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

struct Library_SpawnDev_Crypto_SpawnDev_Crypto_Ed25519
{
    NANOCLR_NATIVE_DECLARE(GenerateKeyPair___STATIC__VOID__SZARRAY_U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(KeyPairFromSeed___STATIC__VOID__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Sign___STATIC__VOID__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Verify___STATIC__BOOLEAN__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1);

    //--//
};

struct Library_SpawnDev_Crypto_SpawnDev_Crypto_X25519
{
    NANOCLR_NATIVE_DECLARE(GeneratePrivateKey___STATIC__VOID__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(GetPublicKey___STATIC__VOID__SZARRAY_U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(SharedSecret___STATIC__VOID__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1);

    //--//
};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SpawnDev_Crypto;

#endif // SPAWNDEV_CRYPTO_H
