//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "SpawnDev_WebRTC.h"
#include "SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection.h"

using namespace SpawnDev_WebRTC::SpawnDev_WebRTC;


HRESULT Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::Create___STATIC__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int retValue = PeerConnection::Create(  hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_INT32( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::CreateDataChannel___STATIC__VOID__I4__STRING( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        const char* param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_LPCSTR( stack, 1, param1 ) );

        PeerConnection::CreateDataChannel( param0, param1, hr );
        NANOCLR_CHECK_HRESULT( hr );

    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::CreateOffer___STATIC__VOID__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        PeerConnection::CreateOffer( param0, hr );
        NANOCLR_CHECK_HRESULT( hr );

    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::CreateAnswer___STATIC__VOID__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        PeerConnection::CreateAnswer( param0, hr );
        NANOCLR_CHECK_HRESULT( hr );

    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::SetRemoteDescription___STATIC__VOID__I4__STRING__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        const char* param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_LPCSTR( stack, 1, param1 ) );

        signed int param2;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 2, param2 ) );

        PeerConnection::SetRemoteDescription( param0, param1, param2, hr );
        NANOCLR_CHECK_HRESULT( hr );

    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::AddIceCandidate___STATIC__VOID__I4__STRING( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        const char* param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_LPCSTR( stack, 1, param1 ) );

        PeerConnection::AddIceCandidate( param0, param1, hr );
        NANOCLR_CHECK_HRESULT( hr );

    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::GetLocalSdpLength___STATIC__I4__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        signed int retValue = PeerConnection::GetLocalSdpLength( param0, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_INT32( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::GetLocalSdp___STATIC__VOID__I4__SZARRAY_U1( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        CLR_RT_TypedArray_UINT8 param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_UINT8_ARRAY( stack, 1, param1 ) );

        PeerConnection::GetLocalSdp( param0, param1, hr );
        NANOCLR_CHECK_HRESULT( hr );

    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::Send___STATIC__I4__I4__SZARRAY_U1__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        CLR_RT_TypedArray_UINT8 param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_UINT8_ARRAY( stack, 1, param1 ) );

        signed int param2;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 2, param2 ) );

        signed int retValue = PeerConnection::Send( param0, param1, param2, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_INT32( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::TryReceive___STATIC__I4__I4__SZARRAY_U1( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        CLR_RT_TypedArray_UINT8 param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_UINT8_ARRAY( stack, 1, param1 ) );

        signed int retValue = PeerConnection::TryReceive( param0, param1, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_INT32( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::GetState___STATIC__I4__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        signed int retValue = PeerConnection::GetState( param0, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_INT32( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::Close___STATIC__VOID__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        PeerConnection::Close( param0, hr );
        NANOCLR_CHECK_HRESULT( hr );

    }
    NANOCLR_NOCLEANUP();
}
