//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "SpawnDev_WebRTC.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::Create___STATIC__I4,
    Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::CreateDataChannel___STATIC__VOID__I4__STRING,
    Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::CreateOffer___STATIC__VOID__I4,
    Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::CreateAnswer___STATIC__VOID__I4,
    Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::SetRemoteDescription___STATIC__VOID__I4__STRING__I4,
    Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::AddIceCandidate___STATIC__VOID__I4__STRING,
    Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::GetLocalSdpLength___STATIC__I4__I4,
    Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::GetLocalSdp___STATIC__VOID__I4__SZARRAY_U1,
    Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::Send___STATIC__I4__I4__SZARRAY_U1__I4,
    Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::TryReceive___STATIC__I4__I4__SZARRAY_U1,
    Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::GetState___STATIC__I4__I4,
    Library_SpawnDev_WebRTC_SpawnDev_WebRTC_PeerConnection::Close___STATIC__VOID__I4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SpawnDev_WebRTC =
{
    "SpawnDev.WebRTC",
    0xD3101139,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
